# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a7db49394bfec100b10f31a12f89f98d"
application_url = "https://bali-census-definitely-startup.trycloudflare.com"
embedded = true
name = "bulk-product-edit"
handle = "bulk-product-edit-6"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://bali-census-definitely-startup.trycloudflare.com/auth/callback",
  "https://bali-census-definitely-startup.trycloudflare.com/auth/shopify/callback",
  "https://bali-census-definitely-startup.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
